### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by KrishAgarwal2811** [Wixonic/WixOS#1]
I logged in to the site then the results were unexpected. 
I have some screen shots. 
![Screenshot_2021-05-13-12-05-02-762_com android chrome](https://user-images.githubusercontent.com/68506145/118088316-8332ec00-b3e4-11eb-829e-de169c8de3aa.jpg)
![Screenshot_2021-05-13-12-04-58-119_com android chrome](https://user-images.githubusercontent.com/68506145/118088321-85954600-b3e4-11eb-8a8c-776b1164fa01.jpg)

**Browse:** Chrome. 
**OS        :** Android

**Comment by Wixonic** [comment]
Hello @KrishAgarwal2811,

Thank you for report this 🤗
